on: push

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
    - name: default shell
      id: poof
      run: echo "SAL=fi" >> $GITHUB_OUTPUT
    - name: python shell
      id: set-var
      run: |
        import os
        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            print('VAL=dddd', file=f)
      shell: python
    - name: print value
      run: |
        echo "the value is ${{ steps.set-var.outputs.VAL }}"
        echo "the value was ${{ steps.poof.outputs.SAL }}"
        
